version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    volumes:
      - ../src:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres+asyncpg://user:password@db:5432/testdb
    depends_on:
      - db

volumes:
  postgres_data:
