"""create user table

Revision ID: 50243194fbdb
Revises: 
Create Date: 2025-08-13 18:47:21.695861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50243194fbdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
