"""2

Revision ID: 96fd061e6733
Revises: 50243194fbdb
Create Date: 2025-08-13 18:49:22.440160

"""


# revision identifiers, used by Alembic.
revision = '96fd061e6733'
down_revision = '50243194fbdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
